# Copyright (c) 2020 Michel Stempin <michel.stempin@funkey-project.com>

# This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License

# Project information
site_name: FunKey Project Documentation
site_author: Michel Stempin
site_description: >-
  FunKey S - the world's smallest foldable handeld console
  Ultra-compact, foldable, powerful and comfortable, the FunKey S is
  the perfect handheld for playing retrogames anywhere, anytime.

# Copyright
copyright: >
  &copy; 2020-2021 FunKey Project<br/>
  Last updated on 2021-01-16<br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
  </a><br />This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
repo_url: 'https://github.com/FunKey-Project/FunKey-Project.github.io'
edit_uri: ''

# Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/favicon.png
  palette:
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono

  # 404 page
  static_templates:
    - 404.html

# Plugins
plugins:
  - search
  - section-index
  - minify:
      minify_html: true
  - exclude:
      glob:
        - tutorials/hardware/force_shutdown.md
        - tutorials/software/restore_games.md
        - tutorials/software/create_themes.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FunKeyProjectOfficial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FunKeyProject
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/funkey_project/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCm6RThJXazA1VMhimqOtjww
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.fr/davidlarbi/funkey-project/
    - icon: fontawesome/brands/github
      link: https://github.com/FunKey-Project
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/funkeyproject/funkey-os/

# Custom CSS
extra_css:
  - 'assets/css/custom.css'
  - 'assets/css/simple-lightbox.min.css'

# Custom JS
extra_javascript:
  - 'assets/js/jquery-3.5.1.min.js'
  - 'assets/js/simple-lightbox.jquery.min.js'
  - 'assets/js/custom.js'

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: FunKey-Project
      repo: FunKey-Project.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 'Overview': 'index.md'
  - "User's Manual":
    - 'Quickstart': 'quickstart.md'
    - Product Description:
      - 'Key Mapping': 'features/key_mapping.md'
      - 'Launchers': 'features/launchers.md'
      - 'Emulators': 'features/emulators.md'
      - 'Standalone Games & Applications': 'features/games_apps.md'
      - 'FunKey Menu': 'features/funkey_menu.md'
      - 'Folder Organization': 'features/folder_organization.md'
      - 'Quick Save': 'features/quick_save.md'
      - 'Instant Action': 'features/instant_action.md'
    - Tutorials:
      - Software:
        - 'Add New ROMs': 'tutorials/software/add_roms.md'
        - 'Add OPK Files': 'tutorials/software/add_opk.md'
        - 'Install the GBA/PS1 BIOS': 'tutorials/software/gba_bios.md'
        - 'Change Aspect Ratio': 'tutorials/software/aspect_ratio.md'
        - 'Take a Snapshot': 'tutorials/software/snapshot.md'
        - 'Firmware Upgrade': 'tutorials/software/firmware_update.md'
        - 'Change Gameboy Palette': 'tutorials/software/gb_palette.md'
        # - 'Create Themes': 'tutorials/software/create_themes.md'
        #- 'Restore Default Games & Emulators': 'tutorials/software/restore_games.md'
      - Hardware:
        - 'Teardown': 'tutorials/hardware/teardown.md'
        - 'Flash & Change micro-SD Card': 'tutorials/hardware/flash_change_sd_card.md'
        - 'Change the Buttons': 'tutorials/hardware/change_buttons.md'
       # - 'Force Shutdown': 'tutorials/hardware/force_shutdown.md'
  - "Developer's Guide":
    - Hardware Reference:
      - 'developers/hardware_reference/index.md'
      - 'Architecture': 'developers/hardware_reference/architecture.md'
      - 'BOM': 'https://htmlpreview.github.io/?https://github.com/FunKey-Project/FunKey-S-Hardware/blob/master/BOM/ibom.html'
      - 'CPU': 'developers/hardware_reference/cpu.md'
      - Power:
        - 'Regulated DC Power Supply Topologies': 'developers/hardware_reference/power/power_supplies_topologies.md'
        - 'Multiple Power Supply Voltages': 'developers/hardware_reference/power/multiple_voltages.md'
        - 'PMIC': 'developers/hardware_reference/power/pmic.md'
        - 'DRAM Power': 'developers/hardware_reference/power/dram_power.md'
        - 'Decoupling' : 'developers/hardware_reference/power/decoupling.md'
      - 'Screen': 'developers/hardware_reference/screen.md'
      - 'Audio': 'developers/hardware_reference/audio.md'
      - 'Buttons': 'developers/hardware_reference/buttons.md'
      - 'SD Card': 'developers/hardware_reference/sd-card.md'
      - 'USB': 'developers/hardware_reference/usb.md'
      - 'UART': 'developers/hardware_reference/uart.md'
      - 'Magnetic Switch': 'developers/hardware_reference/magnetic_switch.md'
    - Software Reference:
      - 'developers/software_reference/index.md'
      - Boot Process:
        - 'developers/software_reference/boot_process/index.md'
        - 'Bootloader': 'developers/software_reference/boot_process/bootloader.md'
        - 'Kernel': 'developers/software_reference/boot_process/kernel.md'
        - 'Init Scripts': 'developers/software_reference/boot_process/init_scripts.md'
        - 'Shutdown Process': 'developers/software_reference/boot_process/shutdown_process.md'
      - SD-Card Layout:
        - 'developers/software_reference/sd_card_layout/index.md'
        - 'Partition Map': 'developers/software_reference/sd_card_layout/partition_map.md'
        - 'Recovery Partition': 'developers/software_reference/sd_card_layout/recovery_partition.md'
        - 'Root Filesystem Partition': 'developers/software_reference/sd_card_layout/root_filesystem_partition.md'
        - 'USB Shared Partition': 'developers/software_reference/sd_card_layout/usb_shared_partition.md'
      - 'Video Processing': 'developers/software_reference/video_processing.md'
      - 'Input Mapping': 'developers/software_reference/input_mapping.md'
    - Tutorials:
      - 'Access the Recovery Boot Mode': 'developers/tutorials/access_recovery.md'
      - 'SSH Connection over USB': 'developers/tutorials/ssh_connection.md'
      - 'Serial Connection over UART': 'developers/tutorials/uart_connection.md'
      - Build System:
        - 'developers/tutorials/build_system/index.md'
        - 'Compilation Environments': 'developers/tutorials/build_system/compilation_environments.md'
        - 'Compile SDK': 'developers/tutorials/build_system/compile_sdk.md'
        - 'Compile Distribution': 'developers/tutorials/build_system/compile_distribution.md'
      - 'Build Programs using SDK': 'developers/tutorials/build_system/build_program_using_sdk.md'
  - Miscellaneous:
    - 'Glossary': 'miscellaneous/glossary.md'
    - 'FAQ': 'miscellaneous/faq.md'
 
