# Copyright (c) 2020 Michel Stempin <michel.stempin@funkey-project.com>

# This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License

# Project information
site_name: FunKey Project Documentation
site_author: Michel Stempin
site_description: >-
  FunKey S - the world's smallest foldable handeld console
  Ultra-compact, foldable, powerful and comfortable, the FunKey S is
  the perfect handheld for playing retrogames anywhere, anytime.

# Copyright
copyright: >
  &copy; 2020-2021 FunKey Project<br/>
  Last updated on 2021-01-16<br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
  </a><br />This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
repo_url: 'https://github.com/FunKey-Project/FunKey-Project.github.io'

# Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/favicon.png
  palette:
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono

  # 404 page
  static_templates:
    - 404.html

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FunKeyProjectOfficial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FunKeyProject
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/funkey_project/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCm6RThJXazA1VMhimqOtjww
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.fr/davidlarbi/funkey-project/
    - icon: fontawesome/brands/github
      link: https://github.com/FunKey-Project
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/funkeyproject/funkey-os/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: FunKey-Project
      repo: FunKey-Project.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 'Overview': 'index.md'
  - User's manual:
    - 'Quickstart': 'quickstart.md'
    - Product description:
      - 'Key mapping': 'features/key_mapping.md'
      - 'Launchers': 'features/launchers.md'
      - 'Emulators': 'features/emulators.md'
      - 'Standalone games & applications': 'features/games_apps.md'
      - 'FunKey menu': 'features/funkey_menu.md'
      - 'Folder organization': 'features/folder_organization.md'
      - 'Auto save and reload': 'features/quick_save.md'
      - 'Instant action': 'features/instant_action.md'
    - Tutorials:
      - Software:
        - 'Add new ROMs': 'tutorials/software/add_roms.md'
        - 'Add OPK files': 'tutorials/software/copy_opk.md'
        - 'Install the GBA/PS1 BIOS': 'tutorials/software/gba_bios.md'
        - 'Change aspect ratio': 'tutorials/software/aspect_ratio.md'
        - 'Take a snapshot': 'tutorials/software/snapshot.md'
        - 'Firmware upgrade': 'tutorials/software/update.md'
        - 'Create themes': 'tutorials/software/themes.md'
        - 'Restore default games & emulators': 'tutorials/software/restore_games.md'
      - Hardware:
        - 'Open/close the console': 'tutorials/hardware/open_console.md'
        - 'Flash & change the SD card': 'tutorials/hardware/change_sd_card.md'
        - 'Change the buttons': 'tutorials/hardware/buttons.md'
        - 'Force shutdown': 'tutorials/hardware/force_shutdown.md'
  - Developer's Guide:
    - Hardware reference:
      - 'Design' : 'developers/hardware_ref/design.md'
      - 'Architecture': 'developers/hardware_ref/architecture.md'
      - 'BOM': 'https://htmlpreview.github.io/?https://github.com/FunKey-Project/FunKey-S-Hardware/blob/master/BOM/ibom.html'
      - 'CPU': 'developers/hardware_ref/cpu.md'
      - Power:
        - 'Regulated DC Power Supply Topologies': 'developers/hardware_ref/power/dc-dc.md'
        - 'Why so many different Power Supply Voltages?': 'developers/hardware_ref/power/voltages.md'
        - 'PMIC': 'developers/hardware_ref/power/pmic.md'
        - 'DRAM Power': 'developers/hardware_ref/power/dram.md'
        - 'Decoupling' : 'developers/hardware_ref/power/decoupling.md'
      - 'Screen': 'developers/hardware_ref/screen.md'
      - 'Audio': 'developers/hardware_ref/audio.md'
      - 'Buttons': 'developers/hardware_ref/buttons.md'
      - 'SD Card': 'developers/hardware_ref/sd-card.md'
      - 'USB': 'developers/hardware_ref/usb.md'
      - 'UART': 'developers/hardware_ref/uart.md'
      - 'Magnetic Switch': 'developers/hardware_ref/magnetic_switch.md'
    - Software reference:
      - 'Software Architecture': 'developers/software_ref/architecture.md'
      - Boot process:
        - 'Introduction': 'developers/software_ref/boot_process/boot_process_intro.md'
        - 'Bootloader': 'developers/software_ref/boot_process/bootloader.md'
        - 'Kernel': 'developers/software_ref/boot_process/kernel.md'
        - 'Init Scripts': 'developers/software_ref/boot_process/init.md'
        - 'Shutdown Process': 'developers/software_ref/boot_process/shutdown.md'
      - Disk mapping:
        - 'Introduction': 'developers/software_ref/disk_mapping/disk_mapping_intro.md'
        - 'Partition Map': 'developers/software_ref/disk_mapping/partition.md'
        - 'Built-in Recovery': 'developers/software_ref/disk_mapping/recovery.md'
        - 'Root Filesystem': 'developers/software_ref/disk_mapping/rootfs.md'
        - 'USB Shared Partition': 'developers/software_ref/disk_mapping/shared.md'
      - 'Video Processing': 'developers/software_ref/video.md'
      - 'Input mapping': 'developers/software_ref/input.md'
    - Tutorials:
      - 'Access the Recovery boot mode': 'developers/tutorials/recovery.md'
      - 'SSH connection over USB': 'developers/tutorials/ssh_connection.md'
      - 'Serial connection over UART': 'developers/tutorials/uart_connection.md'
      - Build System:
        - 'Introduction': 'developers/tutorials/build_system/build_system_intro.md'
        - 'Compilation environments': 'developers/tutorials/build_system/compilation_environments.md'
        - 'Compile SDK': 'developers/tutorials/build_system/toolchain.md'
        - 'Compile distribution': 'developers/tutorials/build_system/build_system.md'
      - 'Build programs using SDK': 'developers/tutorials/build_system/build_program_using_sdk.md'
  - Miscellaneous:
    - 'Glossary': 'miscellaneous/glossary.md'
    - 'FAQ': 'miscellaneous/faq.md'
 
