# Copyright (c) 2020 Michel Stempin <michel.stempin@funkey-project.com>

# This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License

# Project information
site_name: FunKey Project Documentation
site_author: Michel Stempin
site_description: >-
  FunKey S - the world's smallest foldable handeld console
  Ultra-compact, foldable, powerful and comfortable, the FunKey S is
  the perfect handheld for playing retrogames anywhere, anytime.

# Copyright
copyright: >
  &copy; 2020-2021 FunKey Project<br/>
  Last updated on 2021-01-16<br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
  </a><br />This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
repo_url: 'https://github.com/FunKey-Project/FunKey-Project.github.io'

# Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/favicon.png
  palette:
    primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono

  # 404 page
  static_templates:
    - 404.html

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FunKeyProjectOfficial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FunKeyProject
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/funkey_project/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCm6RThJXazA1VMhimqOtjww
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.fr/davidlarbi/funkey-project/
    - icon: fontawesome/brands/github
      link: https://github.com/FunKey-Project
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/funkeyproject/funkey-os/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: FunKey-Project
      repo: FunKey-Project.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Overview: index.md
  - Quickstart: 'quickstart.md'
  - Tutorials:
    - 'Firmware upgrade': 'tutorials/update.md'
    - 'Install the GBA BIOS': 'tutorials/gba_bios.md'
    - 'Change the buttons': 'tutorials/buttons.md'
    - 'Access the built-in Recovery': 'tutorials/recovery.md'
    - 'Create themes': 'tutorials/themes.md'
  - Developer's Guide:
    - Hardware:
      - 'Design' : 'developers/hardware/design.md'
      - 'Architecture': 'developers/hardware/architecture.md'
      - 'BOM': 'https://htmlpreview.github.io/?https://github.com/FunKey-Project/FunKey-S-Hardware/blob/master/BOM/ibom.html'
      - 'CPU': 'developers/hardware/cpu.md'
      - 'Power':
        - 'Regulated DC Power Supply Topologies': 'developers/hardware/power/dc-dc.md'
        - 'Why so many different Power Supply Voltages?': 'developers/hardware/power/voltages.md'
        - 'PMIC': 'developers/hardware/power/pmic.md'
        - 'DRAM Power': 'developers/hardware/power/dram.md'
        - 'Decoupling' : 'developers/hardware/power/decoupling.md'
      - 'Screen': 'developers/hardware/screen.md'
      - 'Audio': 'developers/hardware/audio.md'
      - 'Buttons': 'developers/hardware/buttons.md'
      - 'SD Card': 'developers/hardware/sd-card.md'
      - 'USB': 'developers/hardware/usb.md'
      - 'UART': 'developers/hardware/uart.md'
      - 'Magnetic Switch': 'developers/hardware/magnetic_switch.md'
    - Software:
        - 'System':
          - 'Software Architecture': 'developers/software/system/architecture.md'
          - 'Instant Action':
            - 'Boot Process': 'developers/software/system/bootprocess.md'
            - 'Bootloader': 'developers/software/system/bootloader.md'
            - 'Kernel': 'developers/software/system/kernel.md'
            - 'Init Scripts': 'developers/software/system/init.md'
            - 'Shutdown Process': 'developers/software/system/shutdown.md'
          - 'Storage':
            - 'Partition Map': 'developers/software/system/partition.md'
            - 'Built-in Recovery': 'developers/software/system/recovery.md'
            - 'Root Filesystem': 'developers/software/system/rootfs.md'
            - 'USB Shared Partition': 'developers/software/system/shared.md'
          - 'Video Processing': 'developers/software/applications/video.md'
          - 'User Input': 'developers/software/applications/input.md'
          - 'Build System': 'developers/software/applications/build_system.md'
        - 'Applications':
          - 'Toolchain': 'developers/software/applications/toolchain.md'
  - Miscellaneous:
    - 'Glossary': 'miscellaneous/glossary.md'
    - 'FAQ': 'miscellaneous/faq.md'
 
